"""baseline

Revision ID: 666eb0498833
Revises: 
Create Date: 2026-03-03 09:01:18.717909
"""
from alembic import op
import sqlalchemy as sa



revision = '666eb0498833'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address_line1', sa.String(length=120), nullable=True),
    sa.Column('address_line2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('company_logo_path', sa.String(length=500), nullable=True),
    sa.Column('company_logo_updated_at', sa.DateTime(), nullable=True),
    sa.Column('nav_logo_height_px', sa.Integer(), nullable=True),
    sa.Column('navbar_color_hex', sa.String(length=7), nullable=True),
    sa.Column('primary_color_hex', sa.String(length=7), nullable=True),
    sa.Column('show_nav_logo', sa.Boolean(), nullable=True),
    sa.Column('show_nav_title', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_containers_name')
    )
    op.create_index('ix_containers_is_active', 'containers', ['is_active'], unique=False)
    op.create_index('ix_containers_name', 'containers', ['name'], unique=False)
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_destinations_name')
    )
    op.create_index('ix_destinations_is_active', 'destinations', ['is_active'], unique=False)
    op.create_index('ix_destinations_name', 'destinations', ['name'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_drivers_name')
    )
    op.create_index('ix_drivers_is_active', 'drivers', ['is_active'], unique=False)
    op.create_index('ix_drivers_name', 'drivers', ['name'], unique=False)
    op.create_table('ewc_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_6', sa.String(length=6), nullable=False),
    sa.Column('code_display', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hazardous', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_6')
    )
    op.create_index('idx_ewc_codes_active', 'ewc_codes', ['active'], unique=False)
    op.create_index('idx_ewc_codes_code_6', 'ewc_codes', ['code_6'], unique=False)
    op.create_index('idx_ewc_codes_hazardous', 'ewc_codes', ['hazardous'], unique=False)
    op.create_table('ewc_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('replace_mode', sa.Boolean(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('deactivated_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('imported_by', sa.String(length=120), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hauliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('carrier_licence_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_hauliers_name')
    )
    op.create_index('ix_hauliers_is_active', 'hauliers', ['is_active'], unique=False)
    op.create_index('ix_hauliers_name', 'hauliers', ['name'], unique=False)
    op.create_table('haz_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('invoice_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('invoice_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('licences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('nominal_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('print_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_print_templates_code')
    )
    op.create_index('ix_print_templates_document_type', 'print_templates', ['document_type'], unique=False)
    op.create_index('ix_print_templates_is_active', 'print_templates', ['is_active'], unique=False)
    op.create_table('product_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('nominal_code_default', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recyclers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sic_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ticket_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit_type', sa.String(length=10), server_default='COUNT', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_units_name')
    )
    op.create_index('ix_units_is_active', 'units', ['is_active'], unique=False)
    op.create_index('ix_units_name', 'units', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('void_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('reason_type', sa.String(length=20), server_default='TICKET', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'reason_type', name='uq_void_reasons_code_reason_type')
    )
    op.create_table('waste_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('waste_producers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('yards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('invoice_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=120), nullable=True),
    sa.Column('address_line2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('credit_limit_pence', sa.Integer(), nullable=True),
    sa.Column('is_cash_account', sa.Boolean(), nullable=False),
    sa.Column('invoice_frequency_id', sa.Integer(), nullable=True),
    sa.Column('invoice_frequency', sa.String(length=20), nullable=True),
    sa.Column('payment_terms', sa.String(length=120), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('on_stop', sa.Boolean(), nullable=False),
    sa.Column('cash_account', sa.Boolean(), nullable=False),
    sa.Column('do_not_invoice', sa.Boolean(), nullable=False),
    sa.Column('must_have_po', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_frequency_id'], ['invoice_frequencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code')
    )
    op.create_table('print_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=16), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.String(length=32), nullable=False),
    sa.Column('delivery_config', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['print_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_print_destinations_name')
    )
    op.create_index('ix_print_destinations_delivery_type', 'print_destinations', ['delivery_type'], unique=False)
    op.create_index('ix_print_destinations_document_type', 'print_destinations', ['document_type'], unique=False)
    op.create_index('ix_print_destinations_is_active', 'print_destinations', ['is_active'], unique=False)
    op.create_index('ix_print_destinations_template_id', 'print_destinations', ['template_id'], unique=False)
    op.create_index('uq_print_destinations_default_active_doc_type', 'print_destinations', ['document_type'], unique=True, sqlite_where=sa.text('is_default = 1 AND is_active = 1'), postgresql_where=sa.text('is_default AND is_active'))
    op.create_table('print_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['print_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_print_template_versions_template_id', 'print_template_versions', ['template_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sales_only', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('nominal_code_id', sa.Integer(), nullable=True),
    sa.Column('nominal_code', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('account_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('excess_trigger', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('excess_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_hazardous', sa.Boolean(), nullable=False),
    sa.Column('final_disposal', sa.Boolean(), nullable=False),
    sa.Column('used_on_site', sa.Boolean(), nullable=False),
    sa.Column('final_disposal_wip', sa.Boolean(), nullable=False),
    sa.Column('used_on_site_wip', sa.Boolean(), nullable=False),
    sa.Column('ewc_code_id', sa.Integer(), nullable=True),
    sa.Column('default_destination_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ewc_code_id'], ['ewc_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['product_groups.id'], ),
    sa.ForeignKeyConstraint(['nominal_code_id'], ['nominal_codes.id'], ),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customer_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount_decimal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_adjustments_created_at', 'customer_adjustments', ['created_at'], unique=False)
    op.create_index('ix_customer_adjustments_customer_id', 'customer_adjustments', ['customer_id'], unique=False)
    op.create_table('customer_product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_product_prices_customer_id', 'customer_product_prices', ['customer_id'], unique=False)
    op.create_index('ix_customer_product_prices_product_id', 'customer_product_prices', ['product_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('net_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_snapshot_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=15), nullable=False),
    sa.Column('owner_customer_id', sa.Integer(), nullable=True),
    sa.Column('default_customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('default_tare_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('overweight_threshold_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('haulier_id', sa.Integer(), nullable=True),
    sa.Column('default_haulier_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('default_driver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['default_driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['default_haulier_id'], ['hauliers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['haulier_id'], ['hauliers.id'], ),
    sa.ForeignKeyConstraint(['owner_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_table('invoice_voids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=False),
    sa.Column('voided_by', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['reason_id'], ['void_reasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETE', 'VOID', name='ticketstatusenum', native_enum=False), nullable=False),
    sa.Column('direction', sa.Enum('INWARD', 'OUTWARD', name='directionenum', native_enum=False), nullable=False),
    sa.Column('transaction_type', sa.Enum('WASTEIN', 'WASTEOUT', 'SALE', name='transactiontypeenum', native_enum=False), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_reg_text', sa.String(length=15), nullable=True),
    sa.Column('walk_in', sa.Boolean(), nullable=False),
    sa.Column('walk_in_sale', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('ewc_code_6', sa.String(length=6), nullable=True),
    sa.Column('ewc_code_display', sa.String(length=10), nullable=True),
    sa.Column('ewc_description', sa.Text(), nullable=True),
    sa.Column('ewc_hazardous', sa.Boolean(), nullable=True),
    sa.Column('ewc_manual_override', sa.Boolean(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('haulier_id', sa.Integer(), nullable=True),
    sa.Column('carrier_licence_number', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('yard_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('waste_code_id', sa.Integer(), nullable=True),
    sa.Column('waste_producer_customer_id', sa.Integer(), nullable=True),
    sa.Column('waste_producer_source', sa.Enum('CUSTOMER', 'MANUAL', name='wasteproducersourceenum', native_enum=False), nullable=True),
    sa.Column('waste_producer_name', sa.String(length=120), nullable=True),
    sa.Column('waste_producer_address', sa.String(length=1000), nullable=True),
    sa.Column('gross_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tare_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('net_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pricing_basis', sa.String(length=10), nullable=True),
    sa.Column('pricing_unit_name', sa.String(length=120), nullable=True),
    sa.Column('pricing_unit_type', sa.String(length=10), nullable=True),
    sa.Column('pricing_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pricing_qty_snapshot', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('pricing_net_kg_snapshot', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('pricing_billable_qty_snapshot', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('wip_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('dont_invoice', sa.Boolean(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['haulier_id'], ['hauliers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['waste_code_id'], ['waste_codes.id'], ),
    sa.ForeignKeyConstraint(['waste_producer_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['yard_id'], ['yards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_index('ix_tickets_container_id', 'tickets', ['container_id'], unique=False)
    op.create_index('ix_tickets_customer_id', 'tickets', ['customer_id'], unique=False)
    op.create_index('ix_tickets_datetime', 'tickets', ['datetime'], unique=False)
    op.create_index('ix_tickets_destination_id', 'tickets', ['destination_id'], unique=False)
    op.create_index('ix_tickets_driver_id', 'tickets', ['driver_id'], unique=False)
    op.create_index('ix_tickets_haulier_id', 'tickets', ['haulier_id'], unique=False)
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    op.create_index('ix_tickets_vehicle_id', 'tickets', ['vehicle_id'], unique=False)
    op.create_index('ix_tickets_vehicle_reg_text', 'tickets', ['vehicle_reg_text'], unique=False)
    op.create_index('ix_tickets_walk_in_sale', 'tickets', ['walk_in_sale'], unique=False)
    op.create_table('vehicle_tares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('tare_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_snapshot_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=16), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('delivery_type', sa.String(length=32), nullable=False),
    sa.Column('delivery_config_json', sa.JSON(), nullable=False),
    sa.Column('rendered_content', sa.Text(), nullable=True),
    sa.Column('rendered_bytes_base64', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['print_destinations.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['print_templates.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_print_jobs_created_at', 'print_jobs', ['created_at'], unique=False)
    op.create_index('ix_print_jobs_destination_id', 'print_jobs', ['destination_id'], unique=False)
    op.create_index('ix_print_jobs_document_type', 'print_jobs', ['document_type'], unique=False)
    op.create_index('ix_print_jobs_invoice_id', 'print_jobs', ['invoice_id'], unique=False)
    op.create_index('ix_print_jobs_status', 'print_jobs', ['status'], unique=False)
    op.create_index('ix_print_jobs_template_id', 'print_jobs', ['template_id'], unique=False)
    op.create_index('ix_print_jobs_ticket_id', 'print_jobs', ['ticket_id'], unique=False)
    op.create_table('ticket_voids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=False),
    sa.Column('voided_by', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['reason_id'], ['void_reasons.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_voids')
    op.drop_index('ix_print_jobs_ticket_id', table_name='print_jobs')
    op.drop_index('ix_print_jobs_template_id', table_name='print_jobs')
    op.drop_index('ix_print_jobs_status', table_name='print_jobs')
    op.drop_index('ix_print_jobs_invoice_id', table_name='print_jobs')
    op.drop_index('ix_print_jobs_document_type', table_name='print_jobs')
    op.drop_index('ix_print_jobs_destination_id', table_name='print_jobs')
    op.drop_index('ix_print_jobs_created_at', table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_table('invoice_lines')
    op.drop_table('vehicle_tares')
    op.drop_index('ix_tickets_walk_in_sale', table_name='tickets')
    op.drop_index('ix_tickets_vehicle_reg_text', table_name='tickets')
    op.drop_index('ix_tickets_vehicle_id', table_name='tickets')
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.drop_index('ix_tickets_haulier_id', table_name='tickets')
    op.drop_index('ix_tickets_driver_id', table_name='tickets')
    op.drop_index('ix_tickets_destination_id', table_name='tickets')
    op.drop_index('ix_tickets_datetime', table_name='tickets')
    op.drop_index('ix_tickets_customer_id', table_name='tickets')
    op.drop_index('ix_tickets_container_id', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('invoice_voids')
    op.drop_table('vehicles')
    op.drop_table('invoices')
    op.drop_index('ix_customer_product_prices_product_id', table_name='customer_product_prices')
    op.drop_index('ix_customer_product_prices_customer_id', table_name='customer_product_prices')
    op.drop_table('customer_product_prices')
    op.drop_index('ix_customer_adjustments_customer_id', table_name='customer_adjustments')
    op.drop_index('ix_customer_adjustments_created_at', table_name='customer_adjustments')
    op.drop_table('customer_adjustments')
    op.drop_table('products')
    op.drop_index('ix_print_template_versions_template_id', table_name='print_template_versions')
    op.drop_table('print_template_versions')
    op.drop_index('uq_print_destinations_default_active_doc_type', table_name='print_destinations', sqlite_where=sa.text('is_default = 1 AND is_active = 1'), postgresql_where=sa.text('is_default AND is_active'))
    op.drop_index('ix_print_destinations_template_id', table_name='print_destinations')
    op.drop_index('ix_print_destinations_is_active', table_name='print_destinations')
    op.drop_index('ix_print_destinations_document_type', table_name='print_destinations')
    op.drop_index('ix_print_destinations_delivery_type', table_name='print_destinations')
    op.drop_table('print_destinations')
    op.drop_table('customers')
    op.drop_table('yards')
    op.drop_table('waste_producers')
    op.drop_table('waste_codes')
    op.drop_table('void_reasons')
    op.drop_table('vehicle_types')
    op.drop_table('users')
    op.drop_index('ix_units_name', table_name='units')
    op.drop_index('ix_units_is_active', table_name='units')
    op.drop_table('units')
    op.drop_table('ticket_sequences')
    op.drop_table('tax_rates')
    op.drop_table('suppliers')
    op.drop_table('sic_codes')
    op.drop_table('recyclers')
    op.drop_table('product_groups')
    op.drop_index('ix_print_templates_is_active', table_name='print_templates')
    op.drop_index('ix_print_templates_document_type', table_name='print_templates')
    op.drop_table('print_templates')
    op.drop_table('payment_methods')
    op.drop_table('nominal_codes')
    op.drop_table('licences')
    op.drop_table('invoice_sequences')
    op.drop_table('invoice_frequencies')
    op.drop_table('haz_codes')
    op.drop_index('ix_hauliers_name', table_name='hauliers')
    op.drop_index('ix_hauliers_is_active', table_name='hauliers')
    op.drop_table('hauliers')
    op.drop_table('ewc_import_logs')
    op.drop_index('idx_ewc_codes_hazardous', table_name='ewc_codes')
    op.drop_index('idx_ewc_codes_code_6', table_name='ewc_codes')
    op.drop_index('idx_ewc_codes_active', table_name='ewc_codes')
    op.drop_table('ewc_codes')
    op.drop_index('ix_drivers_name', table_name='drivers')
    op.drop_index('ix_drivers_is_active', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_destinations_name', table_name='destinations')
    op.drop_index('ix_destinations_is_active', table_name='destinations')
    op.drop_table('destinations')
    op.drop_table('cost_centers')
    op.drop_table('contractors')
    op.drop_index('ix_containers_name', table_name='containers')
    op.drop_index('ix_containers_is_active', table_name='containers')
    op.drop_table('containers')
    op.drop_table('company_settings')
    op.drop_table('areas')
    # ### end Alembic commands ###
