HELP_TEXT = {
    "product_group": "Optional grouping used for reporting and default nominal-code fallback.",
    "product_type": "Required single choice that controls ticket availability: sale products for SALE tickets, waste products for WASTE IN/OUT tickets.",
    "product_unit": "KG and Tonnes are system-defined weight units and are not selectable here.",
    "product_nominal_code": "Leave blank to inherit the Product Group default nominal code.",
    "product_ewc_code": "Select the waste code used for compliance and reporting.",
    "product_default_destination": "Prefills the destination on tickets when this product is selected. This can be overridden on the ticket if needed.",
    "product_hazardous": "Marks product as hazardous for default compliance behaviour.",
    "product_final_disposal": "Marks this as a disposal/end-destination product. Tickets should capture destination site/company.",
    "product_used_on_site": "Marks this as internal use on your own site (not a disposal transfer).",
    "customer_invoice_frequency": "Used to suggest invoice date ranges when generating invoices.",
    "customer_payment_terms_days": "Days from invoice date used to calculate due date.",
    "customer_payment_terms": "Free-text payment terms shown on invoices.",
    "customer_terms_indicator": "Shows NET days from payment terms. Blank means no fixed terms are configured.",
    "customer_pricing_indicator": "Shows whether this customer has active product price overrides and how many are active.",
    "customer_price_overrides": "Customer-specific prices that override the standard product rate when selected on tickets.",
    "customer_price_override_product": "Select the product to override for this customer.",
    "customer_price_override_price": "Unit price to use for this customer when the selected product is used.",
    "customer_credit_summary": "Read-only account credit snapshot used for operational credit decisions.",
    "customer_credit_summary_limit": "Configured credit limit for this customer account.",
    "customer_credit_summary_outstanding": "Current outstanding exposure from open invoices plus manual adjustments.",
    "customer_credit_summary_available": "Remaining headroom before reaching the credit limit.",
    "customer_credit_summary_status": "Quick account state: owes, clear, or in credit.",
    "customer_account_adjustments": "Manual credits or corrections that adjust outstanding for credit checks without editing invoices.",
    "customer_adjustment_amount": "Use negative values for credits and positive values to increase outstanding.",
    "customer_adjustment_reason": "Categorises why the adjustment was applied for reporting and audit.",
    "customer_adjustment_note": "Required audit note describing the business reason for the adjustment.",
    "customer_on_stop": "Customer can be ticketed but cannot be completed/invoiced while on stop.",
    "customer_do_not_invoice": "Excludes this customer from all invoice generation.",
    "customer_must_have_po": "Requires PO on tickets before they can be invoiced.",
    "vehicle_registration_search": "Search vehicles by full or partial registration.",
    "vehicle_default_tare": "Suggested tare when this vehicle is selected; can still be overridden on the ticket.",
    "vehicle_overweight_threshold": "Optional limit used for overload checks on this vehicle.",
    "vehicle_ticket_defaults": "Auto-fills these values on new tickets when this vehicle is identified.",
    "vehicle_default_customer": "Pre-selects customer on new tickets for this vehicle.",
    "vehicle_default_haulier": "Pre-selects haulier on new tickets for this vehicle.",
    "vehicle_default_driver": "Auto-fills driver on new tickets for this vehicle. You can change it on the ticket.",
    "vehicle_per_container_tares": "Optional tare overrides by container for this vehicle.",
    "ticket_direction": "Sets vehicle movement direction for this ticket.",
    "ticket_transaction_type": "Controls ticket rules by flow type (waste vs sale).",
    "ticket_product": "Product options are filtered by Direction and Transaction type, so only matching products are shown (for example waste in/out or sale).",
    "ticket_walk_in_sale": "Use for cash/card counter sales. No customer invoice generated.",
    "ticket_po_number": "Optional purchase order reference used for customer billing and invoice checks.",
    "ticket_yard": "Optional yard reference for operational tracking.",
    "ticket_area": "Optional area or bay reference for operational tracking.",
    "ticket_weights": "All weights measured in kg.",
    "ticket_readout_kg": "Readout from the weighbridge feed/manual capture. Gross/Tare remain the billing source unless applied.",
    "ticket_billable_quantity": "Used for COUNT products. For WEIGHT products, quantity is derived from weights.",
    "ticket_unit_rate": "Price per unit used to calculate estimated charge. May come from product defaults or customer overrides.",
    "ticket_ewc_code": "Selecting an EWC code drives hazard status; manual edits are treated as override.",
    "ticket_ewc_hazard": "Derived from EWC and used for hazardous compliance checks.",
    "ticket_waste_producer_same_as_customer": "Copies customer details into waste producer fields for this ticket.",
    "ticket_dont_invoice": "When enabled, this ticket is excluded from invoice generation.",
    "ticket_void_reason": "Audit reason required when voiding a ticket.",
    "ticket_credit_limit_banner": "Operational warning only. Saving/completing the ticket is still allowed.",
    "ticket_credit_limit_limit": "Customer credit limit configured on the account.",
    "ticket_credit_limit_outstanding": "Current outstanding amount before this ticket is considered.",
    "ticket_credit_limit_credit_balance": "Credit balance available from negative outstanding (customer in credit).",
    "ticket_credit_limit_this_ticket": "Estimated value of the current ticket, if enough pricing/quantity data is available.",
    "ticket_credit_limit_projected": "Outstanding plus this ticket estimate, used for limit warning thresholds.",
    "ticket_receipt_wip": "WIP: Receipt printing is not part of the current release scope. Uses a separate receipt template path and may change.",
    "invoice_generate_quick_ranges": "Applies common date presets for ticket selection.",
    "invoice_paid_status": "Derived from invoice status and payment record.",
    "invoice_payment_method_summary": "Displays the method recorded when invoice was marked paid.",
    "invoice_payment_method": "Recorded method used to settle this invoice.",
    "invoice_void_reason": "Required audit reason for voiding this invoice.",
}

HELP_TEXT.update(
    {
        "lookup_carrier_licence_number": "Waste carrier licence number used for compliance and printed documentation.",
        "lookup_destination_meaning": "Represents the final site or facility for this material and is used for compliance and reporting.",
        "lookup_container_usage": "Container type is used for operational tracking and reporting.",
    }
)

HELP_TEXT.update(
    {
        "printing_destination_concept": "A destination links one document type, one template, and one delivery method.",
        "printing_template_concept": "A print template controls what the output looks like and what fields are printed.",
        "printing_job_concept": "A print job is the delivery record created each time output is sent.",
        "printing_document_type": "Document type tells the system what you are sending: Ticket, Invoice, or WTN.",
        "printing_template_field": "Template defines layout/content. Change template to change formatting.",
        "printing_delivery_type": "Delivery type decides how output is sent: local browser, network printer, print node, or email.",
        "printing_transport_config": "Delivery config holds connection settings for the selected delivery type.",
        "printing_qz_direct_print": "Turn this on when users should print directly from their workstation browser through QZ Tray. Platform admins manage the secure signing setup separately.",
        "printing_qz_printer_name": "Optional fallback printer name for this destination. Workstation-specific profiles can override it. Leave blank to use the workstation default printer.",
        "printing_default_destination": "Default destinations are used automatically by Send and Preview for each document type.",
        "printing_active_destination": "Inactive destinations are excluded from normal send/preview flows.",
        "printing_yard_scope": "Scope is document-type based. One active default destination is allowed per document type.",
        "printing_send_test_ticket": "Creates a print job using sample ticket data and the selected destination/template.",
        "printing_insert_field_picker": "Click to insert fields like ticket number, customer, weights, and totals.",
        "printing_template_content_editor": "Use Jinja tokens and loops in the template body. Some values may be blank depending on ticket/invoice data.",
        "printing_content_type": "TEXT is best for thermal output. HTML is best for styled layouts and PDF rendering.",
        "printing_single_page_rule": "Avoid height:100vh in templates; use content-based layout to keep print output on one page.",
        "printing_preview_ticket_id": "Enter a numeric ticket ID. If blank or not found, preview uses the latest completed ticket.",
        "printing_jobs_status": "Job status shows delivery state: QUEUED means pending, SENT means success, FAILED means delivery error.",
        "printing_jobs_rendered_output": "Rendered output is the exact payload content generated from the template at print time.",
        "printing_jobs_delivery_snapshot": "Delivery snapshot stores the destination settings used for this job for audit and troubleshooting.",
        "printing_jobs_transport_snapshot": "Delivery snapshot stores the destination settings used for this job for audit and troubleshooting.",
        "printing_jobs_retry": "Retry submits the same job content again using the job's stored delivery settings.",
        "printing_advanced_delivery_json": "Optional raw JSON override for edge cases. Prefer standard fields unless support advises otherwise.",
    }
)

HELP_TEXT.update(
    {
        "company_logo_upload": "Upload the logo used in document headers and (optionally) the top navigation bar. Max size: 2MB. Uploading a file replaces the current logo.",
        "company_nav_logo_size": "Controls logo height in the top navigation bar (20-80px).",
        "company_show_nav_logo": "Toggle whether the logo is shown in the top navigation bar.",
        "company_show_nav_title": "Toggle whether the company name text is shown in the top navigation bar.",
        "company_navbar_color": "Main navigation bar background color (HEX).",
        "company_primary_color": "Primary accent color used for buttons, highlights, and active states.",
        "company_login_email": "Used to sign in to this workspace.",
        "company_document_email_subject_template": "Plain-text subject template. Supported placeholders: {company_name}, {invoice_no}, and {ticket_no}. Ticket email templates also support {final_disposal} and {used_on_site}. Leave blank to use the built-in default.",
        "company_document_email_body_template": "Plain-text body template. Supported placeholders: {company_name}, {invoice_no}, and {ticket_no}. Ticket email templates also support {final_disposal} and {used_on_site}. Leave blank to use the built-in default.",
        "company_invoice_email_placeholders": "Supported placeholders for invoice emails: {company_name}, {invoice_no}. Use {ticket_no} on ticket emails.",
        "company_ticket_email_placeholders": "Supported placeholders for ticket emails: {company_name}, {ticket_no}, {final_disposal}, {used_on_site}. Use {invoice_no} on invoice emails.",
    }
)

HELP_TEXT.update(
    {
        "dashboard_open_tickets": "Open tickets saved in this workspace that still need to be completed or voided.",
        "dashboard_completed_today": "Tickets completed today for this workspace only.",
        "dashboard_total_weight_today": "Total net weight from completed tickets today. Open and void tickets are excluded.",
        "dashboard_invoices_pending": "Issued invoices still awaiting payment or other final closure.",
        "dashboard_overview_activity": "Use the period filter to switch the activity window for charts and activity panels below.",
        "dashboard_ticket_activity": "Shows ticket volume over time for the selected period using ticket counts, not weight.",
        "dashboard_weight_throughput": "Shows completed net weight over time for the selected period so managers can track throughput, not just ticket count.",
        "dashboard_todays_traffic": "Most recent completed tickets from today, newest first, limited to the latest 20 rows.",
        "dashboard_recent_tickets": "Latest ticket activity inside the selected period, including open and completed work.",
        "dashboard_open_ticket_queue": "Tickets that are still open and awaiting completion by operators.",
        "dashboard_invoice_activity": "Recent invoices plus completed tickets that are ready to invoice inside the selected period.",
        "platform_tenant_management": "Platform-only controls for provisioning tenants, checking access state, and opening customer workspaces.",
        "platform_total_tenants": "All configured tenants, including active and disabled workspaces.",
        "platform_initial_admin": "The first tenant-scoped administrator account created for that workspace.",
        "platform_primary_tenant_admin": "The main sign-in and admin account for this tenant workspace.",
        "platform_tenant_users": "Tenant-scoped sign-in accounts for this workspace. Review roles before granting access.",
        "platform_add_tenant_user": "Create another tenant-scoped sign-in for this workspace.",
        "platform_tenant_user_role": "Choose the level of access this user needs in the tenant workspace.",
        "tenant_role_tenant_admin": "Full control of the tenant workspace, users, settings, and operational/admin functions.",
        "tenant_role_operator": "Day-to-day weighbridge and ticket operations, with no user or tenant settings management.",
        "tenant_role_accounts": "Invoicing, payments, and finance/admin tasks, but not operational setup.",
        "tenant_role_read_only": "View-only access. No changes are allowed.",
        "platform_email_settings_scope": "Defines the platform Resend configuration and sender identity used for outbound emails.",
        "platform_email_provider": "Resend is the only outbound email provider supported in this release.",
        "platform_email_resend_api_key": "Resend API key used for outbound emails. Leave blank to keep the current saved key.",
        "platform_email_from_email": "Sender email address shown on outbound emails.",
        "platform_email_from_display_name": "Sender name shown to email recipients.",
        "platform_email_reply_to": "Optional reply-to address shown on outbound emails.",
        "platform_email_test": "Sends a simple test email using the saved platform Resend settings so you can confirm delivery.",
        "platform_qz_settings_scope": "Platform QZ Settings controls whether direct workstation printing is available and shows whether backend signing is healthy.",
        "platform_qz_management_boundary": "Platform admins manage QZ signing credentials once. Tenant admins only choose printer behaviour and never see signing secrets.",
        "platform_qz_toggle": "Use this platform-wide switch to allow or pause direct workstation printing without exposing signing secrets to tenant workspaces.",
        "platform_qz_config_source": "Shows whether QZ is currently using saved platform credentials or falling back to legacy server configuration, plus any validation errors.",
        "platform_qz_validation": "Checks whether the certificate route, sign route, and browser security policy are ready for tenant-facing direct printing.",
        "platform_qz_browser_requirements": "Even when server diagnostics are healthy, each workstation still needs QZ Tray installed, running, and trusted in the local browser session.",
        "platform_ai_defaults_scope": "Platform AI Settings defines backend-controlled defaults only. Tenants can override the AI model and dashboard insights while safety, tenant isolation, and read-only rules stay enforced by the backend.",
        "platform_ai_default_model": "Used whenever a tenant leaves AI model override on platform default. gpt-5-mini is the recommended lower-cost baseline; gpt-5 is more expensive and should only be used when needed.",
        "platform_ai_temperature": "Lower values keep replies more consistent. GPT-5 models use this as safe response-variation guidance rather than a direct raw API override.",
        "platform_ai_max_output_tokens": "Caps assistant response length and spend.",
        "platform_ai_dashboard_default": "Sets the default AI Insights state for tenant dashboards. Tenants left on platform default fall back to this value.",
        "platform_ai_dashboard_cache_ttl": "Reuses recent dashboard insight results per tenant to reduce repeated AI calls.",
        "platform_ai_assistant_user_rate_limit": "Backend assistant request ceiling per signed-in user in a rolling hour.",
        "platform_ai_assistant_tenant_rate_limit": "Backend assistant request ceiling shared across all users in one tenant in a rolling hour.",
        "platform_ai_dashboard_min_refresh": "Minimum time between fresh dashboard insight generations for the same tenant.",
        "platform_ai_dashboard_hourly_limit": "Maximum number of fresh dashboard insight generations allowed per tenant in a rolling hour.",
        "platform_ai_default_response_style": "Default tone guidance for assistant replies. Concise is recommended for most operational users.",
        "platform_ai_default_focus": "Default emphasis for answers. This tunes response style only and does not change permissions or data access.",
        "platform_ai_extra_instructions": "Optional short prompt addendum appended after the backend-controlled prompt. It cannot override safety, read-only, or tenant-isolation rules.",
        "platform_ai_reset_defaults": "Resets the platform AI defaults and usage thresholds back to the safe baseline values.",
        "tenant_ai_overrides_scope": "These settings only change AI behaviour for this tenant. Leave overrides blank to use the platform defaults.",
        "tenant_ai_assistant_enabled": "Shows or hides the AI assistant for this tenant. Backend safeguards still apply.",
        "tenant_ai_model_override": "Pick a different AI model for this tenant, or leave it on the platform default.",
        "tenant_ai_dashboard_override": "Turn dashboard AI insights on or off for this tenant, or leave it on the platform default.",
    }
)
