HELP_TEXT = {
    "product_group": "Optional grouping used for reporting and default nominal-code fallback.",
    "product_nominal_code": "Leave blank to inherit the Product Group default nominal code.",
    "product_ewc_code": "Select the waste code used for compliance and reporting.",
    "product_default_destination": "Auto-fills destination on new tickets when this product is selected.",
    "product_sales_only": "Restricts this product to SALE transactions only.",
    "product_hazardous": "Marks product as hazardous for default compliance behaviour.",
    "product_wip_final_disposal": "WIP: planned flag for final disposal reporting/compliance flows.",
    "product_wip_used_on_site": "WIP: planned flag for internal on-site consumption tracking.",
    "customer_invoice_frequency": "Used to suggest invoice date ranges when generating invoices.",
    "customer_payment_terms_days": "Days from invoice date used to calculate due date.",
    "customer_payment_terms": "Free-text payment terms shown on invoices.",
    "customer_on_stop": "Customer can be ticketed but cannot be completed/invoiced while on stop.",
    "customer_do_not_invoice": "Excludes this customer from all invoice generation.",
    "customer_must_have_po": "Requires PO on tickets before they can be invoiced.",
    "customer_wip_cash_account": "WIP: planned flag for cash/counter account behaviour.",
    "ticket_direction": "Sets vehicle movement direction for this ticket.",
    "ticket_transaction_type": "Controls ticket rules by flow type (waste vs sale).",
    "ticket_walk_in_sale": "Use for cash/card counter sales. No customer invoice generated.",
    "ticket_yard": "Optional yard reference for operational tracking.",
    "ticket_area": "Optional area or bay reference for operational tracking.",
    "ticket_ewc_code": "Selecting an EWC code drives hazard status; manual edits are treated as override.",
    "ticket_ewc_hazard": "Derived from EWC and used for hazardous compliance checks.",
    "ticket_waste_producer_same_as_customer": "Copies customer details into waste producer fields for this ticket.",
    "ticket_dont_invoice": "When enabled, this ticket is excluded from invoice generation.",
    "ticket_void_reason": "Audit reason required when voiding a ticket.",
    "invoice_generate_quick_ranges": "Applies common date presets for ticket selection.",
    "invoice_paid_status": "Derived from invoice status and payment record.",
    "invoice_payment_method_summary": "Displays the method recorded when invoice was marked paid.",
    "invoice_payment_method": "Recorded method used to settle this invoice.",
    "invoice_void_reason": "Required audit reason for voiding this invoice.",
}

