HELP_TEXT = {
    "product_group": "Optional grouping used for reporting and default nominal-code fallback.",
    "product_nominal_code": "Leave blank to inherit the Product Group default nominal code.",
    "product_ewc_code": "Select the waste code used for compliance and reporting.",
    "product_default_destination": "Auto-fills destination on new tickets when this product is selected.",
    "product_sales_only": "Restricts this product to SALE transactions only.",
    "product_hazardous": "Marks product as hazardous for default compliance behaviour.",
    "customer_invoice_frequency": "Used to suggest invoice date ranges when generating invoices.",
    "customer_payment_terms_days": "Days from invoice date used to calculate due date.",
    "customer_payment_terms": "Free-text payment terms shown on invoices.",
    "customer_on_stop": "Customer can be ticketed but cannot be completed/invoiced while on stop.",
    "customer_do_not_invoice": "Excludes this customer from all invoice generation.",
    "customer_must_have_po": "Requires PO on tickets before they can be invoiced.",
    "vehicle_registration_search": "Search vehicles by full or partial registration.",
    "vehicle_default_tare": "Suggested tare when this vehicle is selected; can still be overridden on the ticket.",
    "vehicle_overweight_threshold": "Optional limit used for overload checks on this vehicle.",
    "vehicle_ticket_defaults": "Auto-fills these values on new tickets when this vehicle is identified.",
    "vehicle_default_customer": "Pre-selects customer on new tickets for this vehicle.",
    "vehicle_default_haulier": "Pre-selects haulier on new tickets for this vehicle.",
    "vehicle_per_container_tares": "Optional tare overrides by container for this vehicle.",
    "ticket_direction": "Sets vehicle movement direction for this ticket.",
    "ticket_transaction_type": "Controls ticket rules by flow type (waste vs sale).",
    "ticket_walk_in_sale": "Use for cash/card counter sales. No customer invoice generated.",
    "ticket_yard": "Optional yard reference for operational tracking.",
    "ticket_area": "Optional area or bay reference for operational tracking.",
    "ticket_ewc_code": "Selecting an EWC code drives hazard status; manual edits are treated as override.",
    "ticket_ewc_hazard": "Derived from EWC and used for hazardous compliance checks.",
    "ticket_waste_producer_same_as_customer": "Copies customer details into waste producer fields for this ticket.",
    "ticket_dont_invoice": "When enabled, this ticket is excluded from invoice generation.",
    "ticket_void_reason": "Audit reason required when voiding a ticket.",
    "ticket_receipt_wip": "WIP: Receipt printing is not part of the current release scope. Uses a separate receipt template path and may change.",
    "invoice_generate_quick_ranges": "Applies common date presets for ticket selection.",
    "invoice_paid_status": "Derived from invoice status and payment record.",
    "invoice_payment_method_summary": "Displays the method recorded when invoice was marked paid.",
    "invoice_payment_method": "Recorded method used to settle this invoice.",
    "invoice_void_reason": "Required audit reason for voiding this invoice.",
}

HELP_TEXT.update(
    {
        "lookup_carrier_licence_number": "Waste carrier licence number used for compliance and printed documentation.",
        "lookup_destination_meaning": "Represents the final site or facility for this material and is used for compliance and reporting.",
        "lookup_container_usage": "Container type is used for operational tracking and reporting.",
    }
)

HELP_TEXT.update(
    {
        "printing_overview": "Printing uses destinations (where/how), templates (layout), and jobs (audit trail).",
        "printing_destination_concept": "A destination links one document type, one template, and one delivery method.",
        "printing_template_concept": "A print template controls what the output looks like and what fields are printed.",
        "printing_job_concept": "A print job is the delivery record created each time output is sent.",
        "printing_document_type": "Document type tells the system what you are sending: Ticket, Invoice, or WTN.",
        "printing_template_field": "Template defines layout/content. Change template to change formatting.",
        "printing_delivery_type": "Delivery type decides how output is sent: local browser, network printer, print node, or email.",
        "printing_transport_config": "Delivery config holds connection settings for the selected delivery type.",
        "printing_default_destination": "Default destinations are used automatically by Send and Preview for each document type.",
        "printing_active_destination": "Inactive destinations are excluded from normal send/preview flows.",
        "printing_yard_scope": "Scope is document-type based. One active default destination is allowed per document type.",
        "printing_send_test_ticket": "Creates a print job using sample ticket data and the selected destination/template.",
        "printing_insert_field_picker": "Click to insert fields like ticket number, customer, weights, and totals.",
        "printing_template_content_editor": "Use Jinja tokens and loops in the template body. Some values may be blank depending on ticket/invoice data.",
        "printing_content_type": "TEXT is best for thermal output. HTML is best for styled layouts and PDF rendering.",
        "printing_preview_ticket_id": "Enter a numeric ticket ID. If blank or not found, preview uses the latest completed ticket.",
        "printing_jobs_status": "Job status shows delivery state: QUEUED means pending, SENT means success, FAILED means delivery error.",
        "printing_jobs_rendered_output": "Rendered output is the exact payload content generated from the template at print time.",
        "printing_jobs_delivery_snapshot": "Delivery snapshot stores the destination settings used for this job for audit and troubleshooting.",
        "printing_jobs_retry": "Retry submits the same job content again using the job's stored delivery settings.",
    }
)
